from __future__ import annotations

from dut_cache import FUEL_MAX_VALID_L, FUEL_MIN_VALID_L

__all__ = [
    "STATE_AUTH_WAIT_TOKEN",
    "STATE_MENU",
    "STATE_FIND_QUERY",
    "STATE_WAIT_UNIT",
    "STATE_CF_NAME",
    "STATE_CF_VALUE",
    "STATE_CF_MORE",
    "STATE_CMD_VALUE",
    "STATE_PARAM_QUERY",
    "STATE_REPORT_NAME",
    "STATE_REPORT_PERIOD",
    "STATE_REPORT_FORMAT",
    "STATE_REPORT_WAIT",
    "STATE_EXPORT_MENU",
    "STATE_WLN_EXPORT_WAIT_DATE",
    "STATE_ADD_DUT_WAIT_NAME",
    "ACTIVE_UI_KEY",
    "UI_OBJECTS",
    "UI_ADMIN",
    "OBJECTS_MODE_LIST",
    "OBJECTS_MODE_CARD_IDLE",
    "OBJECTS_MODE_CARD_FLOW_FIELDS",
    "OBJECTS_MODE_CARD_FLOW_REPORTS",
    "OBJECTS_MODE_CARD_FLOW_SENSORS",
    "OBJECTS_MODE_CARD_FLOW_NEARBY",
    "OBJECTS_MODE_CARD_FLOW_COMMAND",
    "SEARCH_GENERATION_KEY",
    "STATS_GENERATION_KEY",
    "STATS_GENERATION_UNIT_KEY",
    "MODE_NONE",
    "MODE_CF",
    "MODE_CMD",
    "MODE_PARAMS",
    "MODE_REPORT",
    "MODE_EXPORT",
    "CF_STAGE_NAME",
    "CF_STAGE_VALUE",
    "CF_STAGE_MORE",
    "CF_DUMP_CALLBACK",
    "CF_DUMP_BUTTON_TEXT",
    "MENU_BUTTON_FIND",
    "MENU_BUTTON_ADMIN",
    "MENU_BUTTON_EXPORT",
    "MENU_BUTTON_WLN_EXPORT",
    "MENU_BUTTON_SETTINGS",
    "EXPORT_JOB_KEY",
    "WLN_EXPORT_KEY",
    "FUEL_MAX_VALID_L",
    "FUEL_MIN_VALID_L",
]


STATE_AUTH_WAIT_TOKEN = 5
STATE_MENU = 10
STATE_FIND_QUERY = 20
STATE_WAIT_UNIT = 30
STATE_CF_NAME = 40
STATE_CF_VALUE = 41
STATE_CF_MORE = 50
STATE_CMD_VALUE = 60
STATE_PARAM_QUERY = 70
STATE_REPORT_NAME = 80
STATE_REPORT_PERIOD = 81
STATE_REPORT_FORMAT = 82
STATE_REPORT_WAIT = 83
STATE_EXPORT_MENU = 90
STATE_WLN_EXPORT_WAIT_DATE = 105
STATE_ADD_DUT_WAIT_NAME = 106

ACTIVE_UI_KEY = "active_ui"
UI_OBJECTS = "objects"
UI_ADMIN = "admin"

OBJECTS_MODE_LIST = "LIST"
OBJECTS_MODE_CARD_IDLE = "CARD_IDLE"
OBJECTS_MODE_CARD_FLOW_FIELDS = "CARD_FLOW_FIELDS"
OBJECTS_MODE_CARD_FLOW_REPORTS = "CARD_FLOW_REPORTS"
OBJECTS_MODE_CARD_FLOW_SENSORS = "CARD_FLOW_SENSORS"
OBJECTS_MODE_CARD_FLOW_NEARBY = "CARD_FLOW_NEARBY"
OBJECTS_MODE_CARD_FLOW_COMMAND = "CARD_FLOW_COMMAND"

SEARCH_GENERATION_KEY = "search_generation_token"
STATS_GENERATION_KEY = "stats_generation_token"
STATS_GENERATION_UNIT_KEY = "stats_generation_unit"

MODE_NONE = "none"
MODE_CF = "cf"
MODE_CMD = "cmd"
MODE_PARAMS = "params"
MODE_REPORT = "report"
MODE_EXPORT = "export"

CF_STAGE_NAME = "name"
CF_STAGE_VALUE = "value"
CF_STAGE_MORE = "more"
CF_DUMP_CALLBACK = "cf:dump"
CF_DUMP_BUTTON_TEXT = "📄 Все поля"

MENU_BUTTON_FIND = "🔍 Найти объект"
MENU_BUTTON_ADMIN = "🛠 Админ панель"
MENU_BUTTON_EXPORT = "📄 Выгрузить отчёт"
MENU_BUTTON_WLN_EXPORT = "📦 Экспорт WLN"
MENU_BUTTON_SETTINGS = "⚙️ Настройки"
EXPORT_JOB_KEY = "export_job"
WLN_EXPORT_KEY = "wln_export"
